In [3]:
import numpy as np

In [1]:
data = np.load(f'datasets/phone-email_0.2.npz')

NameError: name 'np' is not defined

In [9]:
print(data.files)

['edge_index1', 'edge_index2', 'x1', 'x2', 'pos_pairs', 'test_pairs']


In [6]:
#print(data['edge_index1'])
data = np.load(f'datasets/phone-email_0.2.npz')
#X1=data['x1']

#X2=data['x2']
gt=data['pos_pairs']
gt1=data['test_pairs']
#print(data['pos_pairs'])
print(gt)
print(gt1)
print(np.shape(gt))
print(np.shape(gt1))

[[  0   0]
 [  1   1]
 [  4   4]
 [  8   8]
 [ 14  14]
 [ 16  16]
 [ 27  27]
 [ 30  30]
 [ 40  40]
 [ 44  44]
 [ 47  47]
 [ 56  56]
 [ 60  60]
 [ 63  63]
 [ 64  64]
 [ 75  75]
 [ 83  83]
 [ 84  84]
 [ 89  89]
 [ 90  90]
 [ 94  94]
 [ 99  99]
 [100 100]
 [102 102]
 [105 105]
 [107 107]
 [112 112]
 [120 120]
 [122 122]
 [137 137]
 [140 140]
 [141 141]
 [157 157]
 [174 174]
 [177 177]
 [191 191]
 [198 198]
 [203 203]
 [204 204]
 [205 205]
 [208 208]
 [211 211]
 [212 212]
 [215 215]
 [222 222]
 [224 224]
 [225 225]
 [231 231]
 [241 241]
 [243 243]
 [252 252]
 [257 257]
 [267 267]
 [272 272]
 [273 273]
 [283 283]
 [284 284]
 [286 286]
 [289 289]
 [305 305]
 [314 314]
 [317 317]
 [318 318]
 [322 322]
 [324 324]
 [340 340]
 [345 345]
 [346 346]
 [347 347]
 [353 353]
 [356 356]
 [362 362]
 [368 368]
 [395 395]
 [396 396]
 [397 397]
 [407 407]
 [410 410]
 [416 416]
 [434 434]
 [439 439]
 [443 443]
 [444 444]
 [449 449]
 [451 451]
 [456 456]
 [463 463]
 [466 466]
 [471 471]
 [474 474]
 [481 481]

In [27]:
edge_index = np.loadtxt(f'../Data/data/douban/douban_t_edge.txt', dtype=np.int64)
edge_index=edge_index.T
print(edge_index.T)

[[   0  728]
 [   0 3714]
 [   1  160]
 ...
 [3818 3883]
 [3863 3892]
 [3875 3883]]


In [28]:
edge_index1 = data['edge_index1']  # shape (2, num_edges_in_npz)

num_edges_npz = edge_index1.shape[1]
num_edges_txt = edge_index.shape[1]

print(f"Edges in NPZ: {num_edges_npz}")
print(f"Edges in TXT: {num_edges_txt}")
print(f"Difference: {abs(num_edges_npz - num_edges_txt)} edges")

# Optional: check if edges are exactly the same
same = np.array_equal(edge_index1, edge_index)

Edges in NPZ: 16328
Edges in TXT: 7215
Difference: 9113 edges


In [16]:
for name in data.files:
    #if (name=='pos_pairs' or name=='test_pairs'):
    if (True):
        arr = data[name]
        print(f"Name: {name}")
        print(f"  Type:  {type(arr)}")
        print(f"  Shape: {arr.shape}")
        print(f"  Dtype: {arr.dtype}")
    # Show a small preview (safe even for large arrays)
        print(f"  First few elements:\n{arr[:5]}\n")

Name: edge_index1
  Type:  <class 'numpy.ndarray'>
  Shape: (2, 16328)
  Dtype: int64
  First few elements:
[[   0    0    1 ... 3904 3905 3905]
 [ 728 3714  160 ... 3671 2166 3790]]

Name: edge_index2
  Type:  <class 'numpy.ndarray'>
  Shape: (2, 3022)
  Dtype: int64
  First few elements:
[[   0    1    1 ... 1117 1117 1117]
 [ 819  268  592 ...  538  836  896]]

Name: x1
  Type:  <class 'numpy.ndarray'>
  Shape: (3906, 538)
  Dtype: float64
  First few elements:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Name: x2
  Type:  <class 'numpy.ndarray'>
  Shape: (1118, 538)
  Dtype: float64
  First few elements:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Name: pos_pairs
  Type:  <class 'numpy.ndarray'>
  Shape: (223, 2)
  Dtype: uint16
  First few elements:
[[  75  579]
 [  85  126]
 [ 124  573]
 [ 157 1113]
 [ 180 1072]]

Nam

In [12]:
with open(f"../Data/data/phone/phone_ground_True.txt", "w") as f:
    for i in range(1000):
        f.write(f"{i} {i}\n")
f.close

FileNotFoundError: [Errno 2] No such file or directory: 'Data/data/phone/phone_ground_True.txt'